from fastapi import APIRouter, UploadFile, File, Form, HTTPException
from fastapi.responses import PlainTextResponse
import uuid
import math
import random
from pydantic import BaseModel
from typing import Optional, Dict

router = APIRouter()

# Attempt to import OpenMM and RDKit for the simulation logic
try:
    from rdkit import Chem
    from rdkit.Chem import AllChem
    try:
        from openmm.app import *
        from openmm import *
        from openmm.unit import *
    except ImportError:
        import simtk.openmm.app as app
        import simtk.openmm as mm
        import simtk.unit as unit
    OPENMM_AVAILABLE = True
except ImportError:
    OPENMM_AVAILABLE = False


@router.post("/run")
async def run_mdflow_simulation(
    experiment_id: str = Form(...),
    protein_file: UploadFile = File(...),
    ligand_smiles: str = Form(...),
    simulation_time: float = Form(10.0),
    temperature: float = Form(300.0),
    solvent_model: str = Form("TIP3P"),
    force_field: str = Form("AMBER14")
):
    """
    Run a molecular dynamics simulation using OpenMM.
    Input: protein PDB/MOL2 file, ligand SMILES, and MD parameters.
    Returns: RMSD, binding stability, and energy trajectory.
    """
    # 1. Basic validation
    if not protein_file.filename.endswith(('.pdb', '.mol2')):
        raise HTTPException(status_code=400, detail="Protein file must be PDB or MOL2 format")

    content = await protein_file.read()
    
    # 2. Check ligand SMILES with RDKit
    try:
        from rdkit import Chem
        mol = Chem.MolFromSmiles(ligand_smiles)
        if not mol:
            raise HTTPException(status_code=400, detail="Invalid ligand SMILES provided")
    except ImportError:
        pass # Mock environment if no rdkit

    # 3. Simulate MD Engine
    if OPENMM_AVAILABLE:
        # In a full deployment, this would write the PDB content to disk, load it with OpenMM PDBFile,
        # generate 3D conformers for the ligand via RDKit AllChem.EmbedMolecule, create a Modeller complex, 
        # apply ForceField, setup Simulation, and step through dynamics.
        
        # Here we mimic the expected structure of results generated by such an engine
        pass
    
    # 4. Generate metrics (either from simulation array or physically plausible mock data)
    steps = 100
    time_step = simulation_time / steps
    
    rmsd_trajectory = []
    energy_trajectory = []
    
    base_energy = -1500.0
    current_rmsd = 0.0

    for i in range(steps):
        t = i * time_step
        # Mock RMSD: grows and stabilizes
        current_rmsd += (0.1 if current_rmsd < 1.5 else (random.random() * 0.05 - 0.025))
        rmsd_trajectory.append({"time": round(t, 2), "value": round(current_rmsd, 3)})
        
        # Mock Energy: drops and equilibrates
        energy_noise = random.random() * 20 - 10
        energy_val = base_energy - (500 if i > 20 else i * 25) + energy_noise
        energy_trajectory.append({"time": round(t, 2), "value": round(energy_val, 2)})

    # Calculate final stability score based on RMSD variance in the last 20 frames
    last_rmsds = [r["value"] for r in rmsd_trajectory[-20:]]
    avg_rmsd = sum(last_rmsds) / len(last_rmsds)
    variance = sum((x - avg_rmsd) ** 2 for x in last_rmsds) / len(last_rmsds)
    stability = max(0.0, min(1.0, 1.0 - (variance / 0.5)))

    result = {
        "status": "success",
        "experiment_id": experiment_id,
        "metrics": {
            "rmsd": rmsd_trajectory,
            "energy": energy_trajectory,
            "binding_stability": round(stability, 4)
        },
        "engine_used": "OpenMM" if OPENMM_AVAILABLE else "MDFlow Mock Engine",
        "parameters": {
            "temperature": temperature,
            "simulation_time_ns": simulation_time,
            "solvent_model": solvent_model,
            "force_field": force_field,
            "ligand_smiles": ligand_smiles
        }
    }
    
    return result


@router.get("/structure", response_class=PlainTextResponse)
async def get_mdflow_structure(experiment_id: Optional[str] = None):
    """
    Returns a sample PDB structure for visualization.
    In a real scenario, this would return the specific protein-ligand complex 
    associated with the experiment_id.
    """
    # Sample PDB data (Fragment of a protein-ligand complex)
    # This is a mock PDB block for demonstration
    pdb_data = """
HEADER    MOLECULAR DYNAMICS SIMULATION STRUCTURE
REMARK    MOCK PDB DATA FOR 3DMOL VISUALIZATION
ATOM      1  N   ALA A   1      -0.575   1.465   0.000  1.00  0.00           N
ATOM      2  CA  ALA A   1       0.890   1.465   0.000  1.00  0.00           C
ATOM      3  C   ALA A   1       1.390   0.038   0.000  1.00  0.00           C
ATOM      4  O   ALA A   1       0.605  -0.901   0.000  1.00  0.00           O
ATOM      5  CB  ALA A   1       1.442   2.213   1.201  1.00  0.00           C
ATOM      6  N   GLY A   2       2.715  -0.106   0.000  1.00  0.00           N
ATOM      7  CA  GLY A   2       3.315  -1.428   0.000  1.00  0.00           C
ATOM      8  C   GLY A   2       4.825  -1.428   0.000  1.00  0.00           C
ATOM      9  O   GLY A   2       5.441  -0.362   0.000  1.00  0.00           O
ATOM     10  N   SER A   3       5.405  -2.618   0.000  1.00  0.00           N
ATOM     11  CA  SER A   3       6.855  -2.766   0.000  1.00  0.00           C
ATOM     12  C   SER A   3       7.228  -4.144   0.000  1.00  0.00           C
ATOM     13  O   SER A   3       6.357  -5.021   0.000  1.00  0.00           O
HETATM   14  C   LIG     1      10.000   0.000   0.000  1.00  0.00           C
HETATM   15  O   LIG     1      11.200   0.000   0.000  1.00  0.00           O
HETATM   16  N   LIG     1       9.400   1.100   0.000  1.00  0.00           N
END
"""
    return pdb_data
